# Generated by Django 4.0.4 on 2022-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_admin_booking_feedback_futsal_notice_opponentfinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='user'),
            preserve_default=False,
        ),
    ]
