# Generated by Django 4.0.4 on 2022-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='name',
            field=models.TextField(default='THIS'),
            preserve_default=False,
        ),
    ]
