# Generated by Django 4.0.4 on 2022-05-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_futsal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date_organized',
        ),
    ]
