# Generated by Django 4.0.4 on 2022-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_rename_date_booking_date_organized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
