# Generated by Django 4.0.4 on 2022-05-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_alter_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_organized',
            new_name='date',
        ),
    ]
